name: Build and Deploy to Amazon ECS
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: ["win-x64", "linux-x64"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet publish -c Release --runtime ${{ matrix.runtime }}
      # - name: Test with the dotnet CLI
      #   run: dotnet test
      - name: Copy artifacts to addons folder
        run: mkdir -p addons/counterstrikesharp/plugins/GhostPlugin && cp -r bin/Release/net8.0/${{ matrix.runtime }}/*.* addons/counterstrikesharp/plugins/GhostPlugin
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ghost-plugin-${{ matrix.runtime }}.zip
          path: addons
